"""add ticket status category

Revision ID: 5b6e2e54297d
Revises: 42f3765d7f90
Create Date: 2026-10-04 17:42:13.897197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6e2e54297d'
down_revision: Union[str, Sequence[str], None] = '42f3765d7f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status_category', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_tickets_status_category'), 'tickets', ['status_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_status_category'), table_name='tickets')
    op.drop_column('tickets', 'status_category')
    # ### end Alembic commands ###
