"""add project snapshots

Revision ID: dc655cade484
Revises: 5b6e2e54297d
Create Date: 2026-10-04 18:47:06.308587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc655cade484'
down_revision: Union[str, Sequence[str], None] = '5b6e2e54297d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_snapshots_created_at'), 'project_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_snapshots_project_id'), 'project_snapshots', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_snapshots_project_id'), table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_created_at'), table_name='project_snapshots')
    op.drop_table('project_snapshots')
    # ### end Alembic commands ###
