"""create core tables

Revision ID: ff0fa3349180
Revises: 
Create Date: 2026-10-04 15:39:00.720653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0fa3349180'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('github_login', sa.String(length=100), nullable=True),
    sa.Column('jira_account_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_github_login'), 'people', ['github_login'], unique=False)
    op.create_index(op.f('ix_people_jira_account_id'), 'people', ['jira_account_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('github_repo', sa.String(length=200), nullable=True),
    sa.Column('jira_project_key', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('author_login', sa.String(length=100), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('author_email', sa.String(length=320), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('ticket_key', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'sha', name='uq_commit_project_sha')
    )
    op.create_index(op.f('ix_commits_author_login'), 'commits', ['author_login'], unique=False)
    op.create_index(op.f('ix_commits_committed_at'), 'commits', ['committed_at'], unique=False)
    op.create_index(op.f('ix_commits_person_id'), 'commits', ['person_id'], unique=False)
    op.create_index(op.f('ix_commits_project_id'), 'commits', ['project_id'], unique=False)
    op.create_index(op.f('ix_commits_ticket_key'), 'commits', ['ticket_key'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'person_id')
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('author_login', sa.String(length=100), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('changed_files', sa.Integer(), nullable=False),
    sa.Column('review_comments', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('ticket_key', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'number', name='uq_pr_project_number')
    )
    op.create_index(op.f('ix_pull_requests_author_login'), 'pull_requests', ['author_login'], unique=False)
    op.create_index(op.f('ix_pull_requests_created_at'), 'pull_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_pull_requests_person_id'), 'pull_requests', ['person_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_project_id'), 'pull_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_state'), 'pull_requests', ['state'], unique=False)
    op.create_index(op.f('ix_pull_requests_ticket_key'), 'pull_requests', ['ticket_key'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ticket_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('sprint', sa.String(length=100), nullable=True),
    sa.Column('reopen_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assignee_id'), 'tickets', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tickets_key'), 'tickets', ['key'], unique=True)
    op.create_index(op.f('ix_tickets_project_id'), 'tickets', ['project_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('ticket_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_ticket_id', sa.Integer(), nullable=False),
    sa.Column('target_ticket_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['source_ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_links_source_ticket_id'), 'ticket_links', ['source_ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_links_target_ticket_id'), 'ticket_links', ['target_ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_links_target_ticket_id'), table_name='ticket_links')
    op.drop_index(op.f('ix_ticket_links_source_ticket_id'), table_name='ticket_links')
    op.drop_table('ticket_links')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_project_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_key'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assignee_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_pull_requests_ticket_key'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_state'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_project_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_person_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_created_at'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_author_login'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_commits_ticket_key'), table_name='commits')
    op.drop_index(op.f('ix_commits_project_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_person_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_committed_at'), table_name='commits')
    op.drop_index(op.f('ix_commits_author_login'), table_name='commits')
    op.drop_table('commits')
    op.drop_table('projects')
    op.drop_index(op.f('ix_people_jira_account_id'), table_name='people')
    op.drop_index(op.f('ix_people_github_login'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
