"""API endpoints for Decision Agent."""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.api.deps import require_project_access
from app.api.projects import _project_or_404
from app.db.models import Decision
from app.db.session import get_db
from app.decision.engine import generate_decision

router = APIRouter(prefix="/api/projects", tags=["decision"], dependencies=[Depends(require_project_access)])


@router.get("/{project_id}/decision/latest")
def get_latest_decision(project_id: int, db: Session = Depends(get_db)) -> dict:
    """Get the most recent recommendation produced by the Decision Agent."""
    _project_or_404(db, project_id)
    decision = (
        db.query(Decision)
        .filter(Decision.project_id == project_id)
        .order_by(Decision.created_at.desc())
        .first()
    )
    if not decision:
        return {"decision": None}

    return {
        "decision": {
            "id": decision.id,
            "project_id": decision.project_id,
            "issue": decision.issue,
            "root_cause": decision.root_cause,
            "recommended_action": decision.recommended_action,
            "action_type": decision.action_type,
            "target_ticket_key": decision.target_ticket_key,
            "target_person_name": decision.target_person_name,
            "reasoning": decision.reasoning,
            "confidence": decision.confidence,
            "evidence": decision.evidence,
            "status": decision.status,
            "created_at": decision.created_at.isoformat() if decision.created_at else None,
        }
    }


@router.get("/{project_id}/decision/history")
def get_decision_history(project_id: int, db: Session = Depends(get_db)) -> dict:
    """Get past recommendations generated by the Decision Agent."""
    _project_or_404(db, project_id)
    decisions = (
        db.query(Decision)
        .filter(Decision.project_id == project_id)
        .order_by(Decision.created_at.desc())
        .limit(20)
        .all()
    )
    return {
        "history": [
            {
                "id": d.id,
                "issue": d.issue,
                "recommended_action": d.recommended_action,
                "confidence": d.confidence,
                "action_type": d.action_type,
                "status": d.status,
                "created_at": d.created_at.isoformat() if d.created_at else None,
            }
            for d in decisions
        ]
    }


@router.post("/{project_id}/decision/generate")
def create_decision(project_id: int, db: Session = Depends(get_db)) -> dict:
    """Run the Decision Agent to synthesize signals and produce a new recommendation."""
    _project_or_404(db, project_id)
    decision = generate_decision(db, project_id)
    return {
        "decision": {
            "id": decision.id,
            "project_id": decision.project_id,
            "issue": decision.issue,
            "root_cause": decision.root_cause,
            "recommended_action": decision.recommended_action,
            "action_type": decision.action_type,
            "target_ticket_key": decision.target_ticket_key,
            "target_person_name": decision.target_person_name,
            "reasoning": decision.reasoning,
            "confidence": decision.confidence,
            "evidence": decision.evidence,
            "status": decision.status,
            "created_at": decision.created_at.isoformat() if decision.created_at else None,
        }
    }

